---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    region: us-east-1
  tasks:
    - name: To Launch EC2 Instance and Allocate EIP then Assigned to Instance
      ec2:
        region: "{{ region }}"
        key_name: ansible
        instance_type: t2.medium
        image: ami-01ed306a12b7d1c96
        wait: yes
      register: ec2

- name: Associate new EIP for the Instance
  ec2_eip:
    in_vpc: yes
    reuse_existing_ip_allowed: yes
    state: present
    region: "{{ region }}"
    instance_id: "{{ ec2.instance_id }}"
  register: instance_eip
- debug: var=instance_eip.public_ip