---
- name: Playbook for Route table for  Private
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Collect VPC info
      ec2_vpc_net_facts:
        region: "{{region}}"
        filters:
          "tag:Task": VPC
      register: VPC1

    - name: Set up private subnet route table
      ec2_vpc_route_table:
        vpc_id: "{{VPC1.vpcs[0].vpc_id}}"
        region: "{{region}}"
        tags:
          Name: private
        subnets:
          - "{{database_subnet1.subnet.id}}"
          - "{{database_subnet2.subnet.id}}"
          - "{{database_subnet3.subnet.id}}"
        routes:
          - dest: "{{vpc_cidr}}"
      register: private_route_table