---
- name: Playbook for sec groups
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Collect VPC info
      ec2_vpc_net_facts:
        region: "{{region}}"
        filters:
          "tag:Task": VPC
      register: VPC1

    - name: Create Sec Group1
      ec2_group:
        name: "{{SecGroupName}}"
        description: "{{SecGroupDescription}}"
        vpc_id: "{{VPC1.vpcs[0].vpc_id}}"
        region: "{{region}}"
        rules:
          - proto: tcp
            ports:
            - 80
            cidr_ip: "{{HTTP_CIDR}}"
          - proto: tcp
            ports:
            - 22
            cidr_ip: "{{SSH_CIDR}}"
      register: SecGroup